### ISSUE TITLE
Kx134 Data Quality 

### ISSUE THREAD

**Issue by doludiran** [sparkfun/SparkFun_KX13X_Arduino_Library#12]
Hi, I am running these example codes to on the Kionix Kx134 accelerometer. I have the accelerometer at rest and I am printing the output to serial. I noticed that when the ODR is set to default 50Hz the data comes as expected but when I set the ODR to higher values like at 25600hz, the difference in value from sample to sample is very large. what is causing this? what should I do to improve accuracy at 25600hz? Screenshots of some samples are attached. Thanks.
![50hz](https://user-images.githubusercontent.com/42301811/157183352-5ce11017-4f40-4f05-8c1d-32d80301aeae.png)
![25600hz](https://user-images.githubusercontent.com/42301811/157183355-30317594-0fc0-4c6d-946e-2d4b0711e963.png)

**Comment by ahermida69** [comment]
If you leave the sensor stationary, what is the min/max/average for the 50Hz and for the 25600Hz readings?

**Comment by doludiran** [comment]
Thank you for your quick response. I took a 100 samples and here's the results

25600Hz:
                     X-Axis    Y-Axis    Z-Axis
Min:             -0.327     -0.35     0.679
Max:            0.4089    0.3906  1.4
Average:     0.0297    0.0158    1.0206


50Hz:
                     X-Axis    Y-Axis    Z-Axis
Min:             0.0266   0.0117    1.0107
Max:            0.0359    0.0256     1.02
Average:     0.0311    0.01835   1.0145


It seems that averaging makes it better. My concern is that, this will affect frequency spectrum data. If I set the ODR to 25600Hz and I average the points say 100 samples to 1 point, when plotting the FFT for the samples, what will be the sampling rate for that data set?

**Comment by ahermida69** [comment]
What is your g setting? The higher the g setting and sampling rate the more noise you will get.  My suggestion is to run the code multiple times with various ODR values and # of samples to average.  Look at the FFT for each case and the impact on the results.  I don't know your exact requirements or the application so its difficult to suggest more things.

**Comment by doludiran** [comment]
Turns out averaging will not work for my application. I want to be able to sample at 13kHz and above and it is not possible to achieve this with averaging the points. Is there any way to achieve this with less noise? Atleast to get values closer to the 50Hz results for every g range?

**Comment by edspark** [comment]
If you do have other questions please reopen a new issue!
