### ISSUE TITLE
To run multiple sensors through SPI, each time we need to change CS and then call beginSPI?

### ISSUE THREAD

**Issue by SaeidBayat** [sparkfun/SparkFun_KX13X_Arduino_Library#16]

**Comment by edspark** [comment]
Sounds like you're using an old version of the library. When you update you'll find that you'll call an instance of a class for each sensor you're using and then give the chip select to the `begin()` function for each sensor. This is an example of what you might do: 

```c
SparkFun_KX132_SPI kxAccelNumberOne;
SparkFun_KX132_SPI kxAccelNumberTwo;
SparkFun_KX132_SPI kxAccelNumberThree;

.
.
.

kxAccelNumberOne.begin(chipSelectOne);
kxAccelNumberTwo.begin(chipSelectTwo);
kxAccelNumberThree.begin(chipSelectThree);
```

Let me know if you have any more questions.
