### ISSUE TITLE
Arduino library, example4 sketch, typo prevents code from running properly?

### ISSUE THREAD

**Issue by VancouverUmbrella** [sparkfun/SparkFun_KX13X_Arduino_Library#18]
The **example4** sketch in the Arduino library gave me trouble. I suspect a typo on line 85 where the delay is set to 25ms. With that delay, the code didn't work for me. When I edited the delay to 2.5 (i.e. 1000/400), the example ran as I expected.

Independent confirmation of problem(s) in example4:
https://forum.sparkfun.com/viewtopic.php?f=105&t=58836&p=238164#p238164

It might be worthwhile giving all of the KX13xx examples a good going over. The two I tried (1 and 4) both had blocking problems. The code also contains some comments which I thought might be inaccurate or perhaps out of date.

Kind regards,
Andrew

**Comment by edspark** [comment]
You are correct, that's some bad math or some fat fingers. Thank you for the issue!
