### ISSUE TITLE
Bug in setRange

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_KX13X_Arduino_Library#19]
Hi Eli @edspark ,

Just a heads-up that I've found a bug in ```setRange```. Long story short: I added support for the KX134 to the OLA; @VancouverUmbrella tested it in his glider and was seeing the accel data max out at 8g with 64g-mode selected.

https://github.com/sparkfun/OpenLog_Artemis/issues/144#issuecomment-1383511001

The bug is two-fold: ```setRange``` isn't doing a read-modify-write; and the wrong bits are being set (0&1 instead of 3&4):

https://github.com/sparkfun/SparkFun_KX13X_Arduino_Library/blob/3b4b66b647cc83b4e0fc71722cf69a148cab77d1/src/SparkFun_Qwiic_KX13X.cpp#L157-L181

I've fixed this in the release_candidate branch - but haven't tested it yet. (I've run out of time today.)

Please don't be horrified if you look at the number of commits. I've updated the code so it uses the register bitfields you included (thanks!), instead of having 'duplicate' hard-coded bit definitions in the .cpp. It's a big change but makes the code a lot nicer.

Just FYI, there were other gremlins in there too, mostly to do with data being OR'd into the registers. That sets bits, but can't clear them. The bitfields allow setting/clearing in a single call.

I've also updated ```getRawAccelData``` so it can cope with data in the buffer being 8-bit as well as 16. In my mind the new code works, but is currently untested.

I'll test this tomorrow - probably by sticking the OLA and KX134 in an electric drill and taking it for a spin! - and then ask you to review the changes.

Thanks!
Paul

**Comment by PaulZC** [comment]
What could _possibly_ go wrong?!

![image](https://user-images.githubusercontent.com/5690545/212879705-36cd91bd-24a2-4bab-b4fc-675153308264.png)

**Comment by PaulZC** [comment]
So, after I'd retrieved everything from the darkest corners of my office (the SD card had been flung out of the OLA and up onto a top shelf), I got this:

![image](https://user-images.githubusercontent.com/5690545/212883473-37882005-4ee4-4834-a41e-bdff7750c7bb.png)

I think we can safely say we're in 64-g mode...

**Comment by VancouverUmbrella** [comment]
Looking good. You're a brave tester, I see!

**Comment by PaulZC** [comment]
It went a bit like this:

https://youtu.be/dEU7ocjEza0

:-D
