### ISSUE TITLE
yData on all 4 examples has a small typo

### ISSUE THREAD

**Issue by TurnerRussell50** [sparkfun/SparkFun_KX13X_Arduino_Library#3]
The line(s) that should be for 'yData' (line 64 in ex1, 68 in ex2, etc....) currently says 'zData'

**Comment by edspark** [comment]
Issue is fixed with this [commit](https://github.com/sparkfun/SparkFun_KX13X_Arduino_Library/commit/fe539fd4057e09be8fe966793add9d072a1324e1), thanks @TurnerRussell50
