### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_KX13X_Arduino_Library#5]
In the file "SparkFun_Qwiic_KX13X.cpp" there is a Wire.endTransmission() after a Wire.requestFrom() in three places. Those three Wire.endTransmission() should be removed.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

A check if reading the data was okay can be done this way:
```
auto n = _i2cPort->requestFrom(static_cast<uint8_t>(_deviceAddress), static_cast<uint8_t>(1));
if (n == 1) {
  *dataPointer = _i2cPort->read();
  return KX13X_SUCCESS;
} else {
  return KX13X_I2C_ERROR; //Error: Sensor did not ack
}
```

**Comment by edspark** [comment]
Thanks @Koepel, this has been fixed in the latest commit.
