### ISSUE TITLE
setOutputDataRate() bug

### ISSUE THREAD

**Issue by ahermida69** [sparkfun/SparkFun_KX13X_Arduino_Library#6]
The setOutputDataRate() has an issue.  The code

**if( returnError == KX13X_SUCCESS )
    return true;
  else 
    return false;**

prevents the code 

  **if( returnError == KX13X_SUCCESS ){
    accelControl(accelState);
    return true;
  }
  else
    return false;
}**

from being executed.   The 1st code should be deleted.
 

//Address: 0x21, bits[3:0] - default value is 0x06 (50Hz)
//Sets the refresh rate of the accelerometer's data. 
// 0.781 * (2 * (n)) derived from pg. 26 of Techincal Reference Manual
bool QwiicKX13xCore::setOutputDataRate(uint8_t rate){

  if( rate < 0 | rate > 15 )
    return false;

  uint8_t accelState = readAccelState(); // Put it back where we found it.
  accelControl(false); // Can't adjust without putting to sleep

  KX13X_STATUS_t returnError;
  returnError = writeRegister(KX13X_ODCNTL, 0xF0, rate, 0);
/*   // delete this section
if( returnError == KX13X_SUCCESS )
    return true;
  else 
    return false;
*/ 
  if( returnError == KX13X_SUCCESS ){
    accelControl(accelState);
    return true;
  }
  else
    return false;
}

**Comment by edspark** [comment]
Absolutely agree, it looks like extra check to the returnError slipped in there by mistake. Thank you for the issue - getting to the other ones you listed momentarily. 

https://github.com/sparkfun/SparkFun_KX13X_Arduino_Library/commit/17f55ef1ebf7557b57fff96d7fd2cbc5a6af70ac
