### ISSUE TITLE
readOutputDataRate() returns wrong rate

### ISSUE THREAD

**Issue by ahermida69** [sparkfun/SparkFun_KX13X_Arduino_Library#7]
readOutputDataRate() returns the wrong rate value.  The code

return (0.78 * (2 * tempRegVal));   //<------wrong calculation

should be

return (0.781 * pow(2,tempRegVal));

// Address:0x21 , bit[3:0]: default value is: 0x06 (50Hz)
// Gets the accelerometer's output data rate. 
float QwiicKX13xCore::readOutputDataRate(){
  
  uint8_t tempRegVal;
  readRegister(&tempRegVal, KX13X_ODCNTL);
  tempRegVal &= 0x0F;
  tempRegVal = (float)tempRegVal;
  return (0.78 * (2 * tempRegVal));

}

**Comment by edspark** [comment]
Absolutely correct, fixed [here](https://github.com/sparkfun/SparkFun_KX13X_Arduino_Library/commit/0f044761c67af96faa1efa512243f36319c8e2b3).
